name: "ParallelZombies"
version: "1.1"
main: parallelmc.pz.ParallelZombies
api-version: '1.20'
author: EBro912
description: A Zombie Apocalypse plugin for Parallel events
commands:
  startgame:
    description: Force starts the game
    usage: /startgame
    default: op
  endgame:
    description: Force ends the game
    usage: /endgame
    default: op
  volunteer:
    description: Enter a pool of volunteers to start as a zombie
    usage: /volunteer
  votestart:
    description: Vote to start the game
    usage: /votestart
  setmode:
    description: Force sets the current gamemode
    usage: /setmode (gamemode)